In [1]:
import pandas as pd 

order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
products = pd.read_csv("../data/raw/olist_products_dataset.csv")
product_name = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [2]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [3]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [4]:
date_cols = [
    "shipping_limit_date"
]

for col in date_cols:
    order_items[col] = pd.to_datetime(order_items[col])

order_items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

In [5]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [6]:
product_name.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [7]:
#contamos cuantos registros/items tiene cada orden 
items_per_orders = order_items.groupby("order_id") ["order_item_id"].count()
items_per_orders.head(100)

order_id
00010242fe8c5a6d1ba2dd792cb16214    1
00018f77f2f0320c557190d7a144bdd3    1
000229ec398224ef6ca0657da4fc703e    1
00024acbcdf0a6daa1e931b038114c75    1
00042b26cf59d7ce69dfabb4e55b4fd9    1
                                   ..
003cc6161d7a2593f2525cce0c330d32    1
003d0634280ff3d1d3a54459349a6899    1
003d804eef0e1b856881cd18e0cc0d4c    1
003d9fc84ad902adf2265248b5ffe1a4    1
003edccf16bc5ec447f592913b3df2b4    1
Name: order_item_id, Length: 100, dtype: int64

In [8]:
#conteo absoluto (numero de ordenes por tamano de carrito)
(items_per_orders.value_counts(normalize=True) * 100).round(2).head()

order_item_id
1    90.06
2     7.62
3     1.34
4     0.51
5     0.21
Name: proportion, dtype: float64

In [9]:
(items_per_orders.mean().round(2))

np.float64(1.14)

In [10]:
items_per_orders.median()

np.float64(1.0)

In [11]:
(items_per_orders.describe().round(2))

count    98666.00
mean         1.14
std          0.54
min          1.00
25%          1.00
50%          1.00
75%          1.00
max         21.00
Name: order_item_id, dtype: float64

In [12]:
order_items[["price", "freight_value"]].agg(["mean", "median"]).round(2)

         price  freight_value
mean    120.65          19.99
median   74.99          16.26

In [15]:
total_price = order_items["price"].sum()
total_freight = order_items["freight_value"].sum()

freight_ratio = (total_freight/ total_price) * 100

freight_ratio.round(2)

np.float64(16.57)