In [15]:
import pandas as pd

payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

In [16]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [17]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [18]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [19]:
(payments["payment_type"].value_counts(normalize=True) * 100).round(2)

payment_type
credit_card    73.92
boleto         19.04
voucher         5.56
debit_card      1.47
not_defined     0.00
Name: proportion, dtype: float64

In [22]:
payments[payments["payment_type"] == "not_defined"]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [24]:
bad_orders = payments[payments["payment_type"] == "not_defined"]["order_id"]
orders[orders["order_id"].isin(bad_orders)][["order_id", "order_status"]]

                               order_id order_status
1130   00b1cb0320190ca0daa2c88b35206009     canceled
39919  4637ca194b6387e2d538dc89b124b0ee     canceled
40235  c8c528189310eaa44a745b8d9d26908b     canceled

In [25]:
payments.groupby("payment_installments")["payment_value"].agg(["count", "mean", "median"]).round(2)

                      count    mean  median
payment_installments
0                         2   94.32   94.32
1                     52546  112.42   73.34
2                     12413  127.23  109.42
3                     10461  142.54  110.42
4                      7098  163.98  117.18
5                      5239  183.47  125.97
6                      3920  209.85  138.55
7                      1626  187.67  140.07
8                      4268  307.74  212.70
9                       644  203.44   99.92
10                     5328  415.09  239.74
11                       23  124.93  116.51
12                      133  321.68  198.41
13                       16  150.46  136.20
14                       15  167.96  147.07
15                       74  445.55  255.85
16                        5  292.69  167.37
17                        8  174.60  175.10
18                       27  486.48  335.89
20                       17  615.80  458.31
21                        3  243.70  216.05
22                        1  228.71  228.71
23                        1  236.48  236.48
24                       18  610.05  593.88

In [27]:
payments[payments["payment_installments"] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [29]:
payments_fake = payments[payments["payment_installments"] == 0]["order_id"]
orders[orders["order_id"].isin(payments_fake)][["order_id", "order_status"]]

                               order_id order_status
63782  744bade1fcf9ff3f31d860ace076d422    delivered
66368  1a57108394169c0b47d8f876acc9ba2d    delivered